# Site settings
title: TSR
email: thomas.robinson@st-annes.ox.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: "http://ts-robinson.co.uk" # the base hostname & protocol for your site
twitter_username: nosnibor_mot
github_username:  nosnibormot

jekyll-crosspost_to_medium:
  enabled: true
  cache: .cache
  status: public # public | draft | unlisted
  #license: all-rights-reserved
  text: '<p><i>This post originally appeared <a href=\"#{url}\" rel=\"canonical\">on ts-robinson.co.uk</a>.</i></p>'
